---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic
  name: petclinic
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        #- image: sophie/petclinic 
        - image: mycontainerregistrypetclinic.azurecr.io/sz:latest 
          imagePullPolicy: Always
          name: petclinic
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 350m
            limits:
              cpu: 800m
      restartPolicy: Always
