# This workflow will:
#  - build a Java project with Maven
#  - build a docker image and publish it to Azure Container Registry
#  - deploy the image to a AKS cluster

name: Java CI/CD with Maven and Azure

on:
  push:
    branches: [ sophie ]
  pull_request:
    branches: [ sophie ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Caching the Maven dependencies to speed up the workflow exection time
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
   
    # Test and package the source code with Maven    
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Package with Maven
      run: mvn -B package --file pom.xml -P MySQL -DskipTests=true

    # Move the application to the Dockerfile directory
    - name: Move the package to ./tomcat_petclinic/
      run: |
        mv ./target/petclinic.war ./tomcat_petclinic/petclinic.war

